"""made icon required for making an account to visually appeal to audience

Revision ID: 224d565c80aa
Revises: 7475ede0fac9
Create Date: 2025-07-03 19:04:26.297363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224d565c80aa'
down_revision: Union[str, None] = '7475ede0fac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    subscription_frequency_enum = sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='subscriptionfrequency')
    subscription_frequency_enum.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('accounts', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # Convert the column with explicit casting using raw SQL
    op.execute("ALTER TABLE transactions ALTER COLUMN subscription_frequency TYPE subscriptionfrequency USING subscription_frequency::subscriptionfrequency")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First change the column back to VARCHAR
    op.alter_column('transactions', 'subscription_frequency',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='subscriptionfrequency'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    
    # Then drop the enum type
    subscription_frequency_enum = sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='subscriptionfrequency')
    subscription_frequency_enum.drop(op.get_bind(), checkfirst=True)
    
    op.alter_column('categories', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accounts', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
