"""Had to update the transaction table to make sure a title/label was included for each transaction

Revision ID: 34e712801781
Revises: 583c4097f486
Create Date: 2025-05-11 19:21:49.242058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e712801781'
down_revision: Union[str, None] = '583c4097f486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'title')
    # ### end Alembic commands ###
