"""Updated the budget title column

Revision ID: 44ccb9411954
Revises: 5054a30dd3a8
Create Date: 2025-08-11 16:40:04.417534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44ccb9411954'
down_revision: Union[str, None] = '5054a30dd3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the new enum type first
    op.execute("CREATE TYPE auditaction AS ENUM ('UPDATE', 'DELETE')")
    
    # Alter the column to use the new enum type with explicit casting
    op.execute("ALTER TABLE audit_logs ALTER COLUMN action TYPE auditaction USING action::text::auditaction")
    
    # Drop the old enum type
    op.execute("DROP TYPE audit_action")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the old enum type first
    op.execute("CREATE TYPE audit_action AS ENUM ('UPDATE', 'DELETE')")
    
    # Alter the column to use the old enum type with explicit casting
    op.execute("ALTER TABLE audit_logs ALTER COLUMN action TYPE audit_action USING action::text::audit_action")
    
    # Drop the new enum type
    op.execute("DROP TYPE auditaction")
    # ### end Alembic commands ###
