"""Create budget table only

Revision ID: 5054a30dd3a8
Revises: 12c18723f268
Create Date: 2025-08-10 15:12:27.743186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5054a30dd3a8'
down_revision: Union[str, None] = '12c18723f268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('budget_name', sa.String(), nullable=False),
    sa.Column('budget_amount', sa.Float(), nullable=False),
    sa.Column('budget_month', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_index('ix_budgets_budget_month', 'budgets', ['budget_month'], unique=False)
    op.create_index('ix_budgets_category_id', 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index('ix_budgets_category_id', table_name='budgets')
    op.drop_index('ix_budgets_budget_month', table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
