"""Updated relationship casacding for foreign tables besides user

Revision ID: 54a41ccf7568
Revises: 63ae8a2eea32
Create Date: 2025-05-06 22:38:40.030632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a41ccf7568'
down_revision: Union[str, None] = '63ae8a2eea32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
