"""Updated column subscriptions for transactions table

Revision ID: 583c4097f486
Revises: acb544864213
Create Date: 2025-05-11 16:39:47.857670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583c4097f486'
down_revision: Union[str, None] = 'acb544864213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('subscription_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('transactions', 'subscription_end_date')
    op.drop_column('transactions', 'subscription_start_date')
    # ### end Alembic commands ###
