"""add training categorization records table

Revision ID: 59e69375fbc2
Revises: 5b47eb1eb12a
Create Date: 2025-05-16 23:02:56.781282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e69375fbc2'
down_revision: Union[str, None] = '5b47eb1eb12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_categorization_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_categorization_records',

    )
    # ### end Alembic commands ###
