"""add_monthly_snapshots_table

Revision ID: a47a2507ee6a
Revises: 886f124ac3ef
Create Date: 2025-06-21 20:25:59.330802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47a2507ee6a'
down_revision: Union[str, None] = '886f124ac3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the snapshottype enum first
    op.execute("CREATE TYPE snapshottype AS ENUM ('account', 'net_worth', 'budget_progress', 'category_spending')")

    # Create monthly_snapshots table
    op.create_table('monthly_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_type', sa.Enum('account', 'net_worth', 'budget_progress', 'category_spending', name='snapshottype', create_type=False), nullable=False),
    sa.Column('net_worth', sa.Float(), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    
    # Create indexes
    op.create_index('ix_monthly_snapshots_user_snapshot_date', 'monthly_snapshots', ['user_id', 'snapshot_type', 'snapshot_date'])
    op.create_index('ix_monthly_snapshots_account_snapshot_date', 'monthly_snapshots', ['account_id', 'snapshot_type', 'snapshot_date'])
    op.create_index(op.f('ix_monthly_snapshots_account_id'), 'monthly_snapshots', ['account_id'])
    op.create_index(op.f('ix_monthly_snapshots_user_id'), 'monthly_snapshots', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert subscription frequency enum
    op.alter_column('transactions', 'subscription_frequency',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='subscriptionfrequency'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    
    # Drop indexes
    op.drop_index(op.f('ix_monthly_snapshots_user_id'), table_name='monthly_snapshots')
    op.drop_index(op.f('ix_monthly_snapshots_account_id'), table_name='monthly_snapshots')
    op.drop_index('ix_monthly_snapshots_account_snapshot_date', table_name='monthly_snapshots')
    op.drop_index('ix_monthly_snapshots_user_snapshot_date', table_name='monthly_snapshots')
    
    # Drop monthly_snapshots table
    op.drop_table('monthly_snapshots')
    
    # Drop snapshot type enum if it exists
    op.execute("DROP TYPE IF EXISTS snapshottype")
    # ### end Alembic commands ###
