"""Created a more stable table for storing OpenAI category recommendations based on user transaction inputs

Revision ID: ab5f537b8676
Revises: 1b4cad361301
Create Date: 2025-05-17 20:05:29.818971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab5f537b8676'
down_revision: Union[str, None] = '1b4cad361301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_categorization_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_categorization_records',
    sa.Column('record_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_reference', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_reference', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_reference', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_confirmed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('alt_category_suggestion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_reference'], ['categories.category_id'], name='training_categorization_records_category_reference_fkey'),
    sa.ForeignKeyConstraint(['transaction_reference'], ['transactions.transaction_id'], name='training_categorization_records_transaction_reference_fkey'),
    sa.ForeignKeyConstraint(['user_reference'], ['users.user_id'], name='training_categorization_records_user_reference_fkey'),
    sa.PrimaryKeyConstraint('record_id', name='training_categorization_records_pkey')
    )
    # ### end Alembic commands ###
