"""added transaction columns that deals with transaction sources

Revision ID: acb544864213
Revises: ec91a9a6d8d0
Create Date: 2025-05-10 22:10:48.558669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb544864213'
down_revision: Union[str, None] = 'ec91a9a6d8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_account', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_type')
    op.drop_column('transactions', 'payment_account')
    # ### end Alembic commands ###
