"""updated net_worth to become amount for flexibiity in snapshots

Revision ID: b7f13ff7d818
Revises: a47a2507ee6a
Create Date: 2025-06-21 21:25:11.951602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f13ff7d818'
down_revision: Union[str, None] = 'a47a2507ee6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_snapshots', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_column('monthly_snapshots', 'net_worth')
    op.execute("CREATE TYPE snapshottype AS ENUM ('ACCOUNT', 'NET_WORTH', 'BUDGET_PROGRESS', 'CATEGORY_SPENDING')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_snapshots', sa.Column('net_worth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('monthly_snapshots', 'amount')
    # ### end Alembic commands ###
