"""Added an optional 
category description column

Revision ID: b92a89f7a8ff
Revises: 224d565c80aa
Create Date: 2025-07-12 18:23:39.004741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92a89f7a8ff'
down_revision: Union[str, None] = '224d565c80aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'category_description')
    # ### end Alembic commands ###
